### ISSUE TITLE
Add-on 'plugin.video.invidious' is not compatible with Kodi

### ISSUE THREAD

**Issue by Nerdmind** [TheAssassin/kodi-invidious-plugin#7]
Hello.

I am running the latest version of [_OSMC_](https://osmc.tv/) including _Kodi_ 18.9 on a Raspberry Pi 3 B. After installation as described in `README.md`, the graphical user interface throws the following error message if I try to enable it:

> The addon is not compatible with this Kodi version.
> (Translated from German.)

In addition, the `~/.kodi/temp/kodi.log` contains the following error message:

> ERROR: Add-on 'plugin.video.invidious' is not compatible with Kodi

After I looked into the commit logs, I decided to check out commit 6564e98045325512a47403331aca7477f7047be3 and give it a try. It worked! :smile: 

So the problem occurs since the next commit (0d72e4f98b0d9ee79066f213140ae5400f9e584b) which updates the plugin to support _Kodi_ 19.

Does that mean _Kodi_ 18 is no longer supported? Anyway, I wanted to let you know because the `README.md` still says that _Kodi_ 18 is supported but it obviously does not work anymore since the previously mentioned commit. :thinking:

**Comment by TheAssassin** [comment]
Thanks for the hint, I will update the README accordingly. I think I'll create a tag for the older version and link that as well. 

By the way, #6 actually broke the backwards compatibility.
