### ISSUE TITLE
Invidious for leia?

### ISSUE THREAD

**Issue by audiosistem** [TheAssassin/kodi-invidious-plugin#8]
Hi, what can I do?
In matrix v 1.0.8 it works with changed ip address, but 0.0.6 for leia fail.
Can you help me?
Thanks!

**Comment by TheAssassin** [comment]
What exactly are you talking about? This plugin only works in Kodi 19+.

**Comment by audiosistem** [comment]
> What exactly are you talking about? This plugin only works in Kodi 19+.
Perfectly true what you say.At 18, search, find and play, don't keep the history.
Thanks!
![As](https://user-images.githubusercontent.com/6246768/142634345-9bfac9c7-62fd-4425-b86a-397580890b75.jpg)

**Comment by audiosistem** [comment]
No offense ... isn't this your addon?I am aware that the world is evolving.
They are already working on the Nexus, but ...
[plugin.video.invidious-0.0.1~alpha1.zip](https://github.com/TheAssassin/kodi-invidious-plugin/files/7570877/plugin.video.invidious-0.0.1.alpha1.zip)

**Comment by TheAssassin** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Do your homework and provide some meaningful information. There is no actual question, the tiny amount of available information is not helping at all.

**Comment by audiosistem** [comment]
This version works. Search and play in leia.
 Don't keep searching and come back,no history keep,compared to the version for matrix.
Thanks!

**Comment by TheAssassin** [comment]
Again, this plugin only supports Kodi 19+.
